apiVersion: v1
kind: Namespace
metadata:
  name: default # 새로운 네임스페이스 생성
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatwas
  labels:
    app: tomcatwas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcatwas
  template:
    metadata:
      labels:
        app: tomcatwas
    spec:
      containers:
      - name: tomcat
        image: 526002960031.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_tomcat:abdf5db
        resources:
          requests:
            cpu: "30m"
          limits:
            cpu: "50m"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  selector:
    app: tomcatwas
  ports:
    - protocol: TCP
      port: 8080   # Service가 노출하는 포트
      targetPort: 8080 # Pod 내부에서 사용하는 포트
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tomcatwas
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 30
